version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3307"
    ports:
      - "3307:3307"
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/shared:/usr/local/shared
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/custom.cnf
      # - ./mysql/log:/var/log/mysql
    networks:
      - data-layer

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - data-layer

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - data-layer

networks:
  data-layer:
    name: data_layer
