version: "3"

services:
  mysql:
    build: ./mysql/
    restart: always
    env_file: ./mysql/.env
    ports:
      - "3307:3307"
    volumes:
      - ./mysql/shared:/usr/local/shared
      - db:/var/lib/mysql
    networks:
      - backend
  myadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - backend

volumes:
  db:
networks:
  backend:
